version: "3"
services:
  anchor:
    image: dev-anchor-img
    container_name: dev-anchor-inst
    build:
      context: ./dapp/systems
      dockerfile: ./backend/anchor/Dockerfile
    ports:
      - '2345'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - anchordata:/usr/src/data
    networks:
      dev-api-layer:
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5680/poll || kill 1
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  dev-api-layer:
    driver: bridge
volumes:
  anchordata: