version: "3"
services:
  chance:
    image: chance_app_img
    container_name: chance_app_inst
    build:
      context: ./
      dockerfile: ./src/Dockerfile.dev
    ports:
      - '3456:3456'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - chancedata:/usr/chance/data
    networks:
      chance_app_network:
        aliases:
          - chance_app
networks:
  chance_app_network:
    driver: bridge
volumes:
  chancedata: