version: "3"
services:
  chance:
    image: chance-app-img
    container_name: chance-app-inst
    build:
      context: ./app
      dockerfile: ./Dockerfile.dev
    ports:
      - '80:80'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - chancedata:/usr/chance/data
    networks:
      chance-app-network:
        aliases:
          - chance-app
networks:
  chance-app-network:
    driver: bridge
volumes:
  chancedata: