[features]
seeds = false
[programs.localnet]
chance_dapp = "CDBhgokH5qJVnZ1Kd9aW4hQmgBmG1tAifyVFbXmsYymZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sirgallo/Documents/Projects/chanceDapp/target/deploy/chance_dapp-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
