version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: nginx_dev_cont
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - '1234:1234'
    networks:
      dev_app_layer:
    depends_on:
      - chance
  anchor:
    image: dev_anchor_img
    build:
      context: .
      dockerfile: ./backend/anchor/Dockerfile
    ports:
      - '2345'
    environment:
      - NODE_ENV=docker
      - NODE_OPTIONS="--max-old-space-size=4096"
    volumes:
      - anchordata:/usr/src/data
    networks:
      dev_app_layer:
      dev_api_layer:
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5680/poll || kill 1
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  dev_app_layer:
    driver: bridge
  dev_api_layer:
    driver: bridge
volumes:
  anchordata: